### ISSUE TITLE
422 Unprocessable entity

### ISSUE THREAD

**Issue by Xstoudi** [TG908/fork-sync#7]
I've this error : 
```
2020-01-21T12:08:07.8503617Z RequestError [HttpError]: Validation Failed
2020-01-21T12:08:07.8504460Z     at /home/runner/work/_actions/TG908/fork-sync/v1.1.5/node_modules/@octokit/request/dist-node/index.js:66:23
2020-01-21T12:08:07.8528521Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-01-21T12:08:07.8540899Z     at async Job.doExecute (/home/runner/work/_actions/TG908/fork-sync/v1.1.5/node_modules/bottleneck/light.js:405:18) {
2020-01-21T12:08:07.8545446Z   name: 'HttpError',
2020-01-21T12:08:07.8545832Z   status: 422,
2020-01-21T12:08:07.8546033Z   headers: {
2020-01-21T12:08:07.8547372Z     'access-control-allow-origin': '*',
2020-01-21T12:08:07.8548368Z     'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
2020-01-21T12:08:07.8554975Z     connection: 'close',
2020-01-21T12:08:07.8555433Z     'content-length': '217',
2020-01-21T12:08:07.8555885Z     'content-security-policy': "default-src 'none'",
2020-01-21T12:08:07.8556226Z     'content-type': 'application/json; charset=utf-8',
2020-01-21T12:08:07.8556545Z     date: 'Tue, 21 Jan 2020 12:08:07 GMT',
2020-01-21T12:08:07.8556915Z     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2020-01-21T12:08:07.8557235Z     server: 'GitHub.com',
2020-01-21T12:08:07.8557667Z     status: '422 Unprocessable Entity',
2020-01-21T12:08:07.8558012Z     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2020-01-21T12:08:07.8558294Z     'x-content-type-options': 'nosniff',
2020-01-21T12:08:07.8558937Z     'x-frame-options': 'deny',
2020-01-21T12:08:07.8559836Z     'x-github-media-type': 'github.v3; format=json',
2020-01-21T12:08:07.8560190Z     'x-github-request-id': '07C1:06D5:1375B4:310C51:5E26E9A7',
2020-01-21T12:08:07.8560459Z     'x-ratelimit-limit': '5000',
2020-01-21T12:08:07.8560940Z     'x-ratelimit-remaining': '4996',
2020-01-21T12:08:07.8561241Z     'x-ratelimit-reset': '1579609988',
2020-01-21T12:08:07.8561548Z     'x-xss-protection': '1; mode=block'
2020-01-21T12:08:07.8561662Z   },
2020-01-21T12:08:07.8562002Z   request: {
2020-01-21T12:08:07.8562294Z     method: 'POST',
2020-01-21T12:08:07.8562770Z     url: 'https://api.github.com/repos/Xstoudi/rtorrent_exporter/pulls',
2020-01-21T12:08:07.8562947Z     headers: {
2020-01-21T12:08:07.8563274Z       accept: 'application/vnd.github.v3+json',
2020-01-21T12:08:07.8563598Z       'user-agent': 'octokit.js/16.30.1 Node.js/12.13.1 (Linux 5.0; x64)',
2020-01-21T12:08:07.8563866Z       authorization: 'token [REDACTED]',
2020-01-21T12:08:07.8564182Z       'content-type': 'application/json; charset=utf-8'
2020-01-21T12:08:07.8564435Z     },
2020-01-21T12:08:07.8564836Z     body: '{"title":"Fork Sync","head":"Xstoudi:master","base":"master","body":"","merge_method":"merge","maintainer_can_modify":false}',
2020-01-21T12:08:07.8565051Z     request: { hook: [Function: bound bound register], validate: [Object] }
2020-01-21T12:08:07.8565167Z   },
2020-01-21T12:08:07.8565310Z   errors: [
2020-01-21T12:08:07.8565455Z     {
2020-01-21T12:08:07.8565769Z       resource: 'PullRequest',
2020-01-21T12:08:07.8566012Z       code: 'custom',
2020-01-21T12:08:07.8566318Z       message: 'No commits between master and master'
2020-01-21T12:08:07.8566474Z     }
2020-01-21T12:08:07.8566616Z   ],
2020-01-21T12:08:07.8567186Z   documentation_url: 'https://developer.github.com/v3/pulls/#create-a-pull-request'
2020-01-21T12:08:07.8567381Z }
2020-01-21T12:08:07.8570570Z ##[error]Failed to create or merge pull request
2020-01-21T12:08:07.8583426Z ##[error]Node run failed with exit code 1
```

**Comment by TG908** [comment]
It looks like you are trying to merge `Xstoudi:master` into `Xstoudi:master`. Make sure to set `owner` to the owner of the repository you forked from.

**Comment by kiranshahavi** [comment]
Am facing this please help me with this this




response: {
    url: 'https://api.github.com/repos/kiranshahavi/blogdata/pulls',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '223',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 13 Oct 2022 10:40:51 GMT',
      'github-authentication-token-expiration': '2022-11-12 10:31:26 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': '',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'FBF7:0F00:7A846:84170:6347EB33',
      'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4982',
      'x-ratelimit-reset': '1665659290',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '18',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/kiranshahavi/blogdata/pulls',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/2.0.8 octokit-core.js/4.1.0 Node.js/16.13.0 (win32; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"owner":"kiranshahavi","repo":"blogdata","head":"master","base":"master"}',
    request: { hook: [Function: bound bound register] }
  }
}
DEBUG2 HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between master and master"}
    at C:\Git\uploadserverfiles\node_modules\@octokit\request\dist-node\index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (C:\Git\uploadserverfiles\node_modules\bottleneck\light.js:405:18)
